"""empty message

Revision ID: 06cfaa72376a
Revises: 958c731414d6
Create Date: 2021-02-16 23:53:46.270980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06cfaa72376a'
down_revision = '958c731414d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'testint', ['id'])
    op.create_unique_constraint(None, 'testuuid', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testuuid', type_='unique')
    op.drop_constraint(None, 'testint', type_='unique')
    # ### end Alembic commands ###
